export type EditorCommandId =
  | "undo"
  | "redo"
  | "find"
  | "findReplace"
  | "findNext"
  | "findPrevious"
  | "goToDefinition"
  | "closeFind"
  | "toggleFindCaseSensitive"
  | "toggleFindWholeWord"
  | "toggleFindRegex"
  | "toggleFindInSelection"
  | "togglePreserveCase"
  | "replaceOne"
  | "replaceAll"
  | "selectAllMatches"
  | "selectAll"
  | "addNextOccurrence"
  | "clearSecondarySelections"
  | "deleteBackward"
  | "deleteForward"
  | "indentSelection"
  | "outdentSelection"
  | "cursorLeft"
  | "cursorRight"
  | "cursorUp"
  | "cursorDown"
  | "selectLeft"
  | "selectRight"
  | "selectUp"
  | "selectDown"
  | "cursorWordLeft"
  | "cursorWordRight"
  | "selectWordLeft"
  | "selectWordRight"
  | "cursorLineStart"
  | "cursorLineEnd"
  | "selectLineStart"
  | "selectLineEnd"
  | "cursorPageUp"
  | "cursorPageDown"
  | "selectPageUp"
  | "selectPageDown"
  | "cursorDocumentStart"
  | "cursorDocumentEnd"
  | "selectDocumentStart"
  | "selectDocumentEnd";

export type EditorCommandContext = {
  readonly event?: KeyboardEvent;
};
