export type {
  Anchor as PieceTableAnchor,
  AnchorBias,
  AnchorLiveness,
  Piece,
  PieceBufferId,
  PieceTableEdit,
  PieceTableSnapshot,
  Point,
  RealAnchor,
  ResolvedAnchor,
} from './pieceTableTypes'

export {
  Anchor,
  anchorAfter,
  anchorAt,
  anchorBefore,
  applyBatchToPieceTable,
  compareAnchors,
  createPieceTableSnapshot,
  deleteFromPieceTable,
  debugPieceTable,
  forEachPieceTableTextChunk,
  getPieceTableLength,
  getPieceTableOriginalText,
  getPieceTableText,
  insertIntoPieceTable,
  offsetToPoint,
  pieceTableSnapshotsHaveSameText,
  pointToOffset,
  resolveAnchor,
  resolveAnchorLinear,
} from './pieceTable'
