export {
  Anchor,
  anchorAfter,
  anchorAt,
  anchorBefore,
  applyBatchToPieceTable,
  createPieceTableSnapshot,
  createPieceTableWalker,
  deleteFromPieceTable,
  diffPieceTableSnapshots,
  forEachPieceTableTextChunk,
  getPieceTableLength,
  insertIntoPieceTable,
  materializePieceTableFullText,
  offsetToPoint,
  pieceTableSnapshotsHaveSameText,
  pointToOffset,
  readPieceTableTextRange,
  resolveAnchor,
  streamPieceTablePieces,
  streamPieceTableTextChunks,
} from '../pieceTable'
export {
  createDocumentSession,
  createEditorBufferSession,
  createEditorTextBuffer,
  createEditorViewSession,
  createStaticDocumentSession,
} from '../documentSession'
export { createDocumentTextSnapshot, createStringTextSnapshot } from '../documentTextSnapshot'
export {
  characterClassAt,
  clampTextOffset,
  clampTextOffsetRange,
  codePointSizeAt,
  compareTextOffsetRanges,
  isWholeWordRange,
  isWordCodePointAt,
  isWordCodePointBefore,
  lineRangeAtOffset,
  nextCodePointOffset,
  nextWordOffset,
  normalizeTextOffsetRanges,
  previousCodePointOffset,
  previousCodePointStart,
  previousWordOffset,
  wordRangeAtOffset,
} from '../textRanges'
export type {
  AnchorBias,
  AnchorLiveness,
  PieceTableAnchor,
  PieceTableEdit,
  PieceTableSnapshot,
  PieceTableWalker,
  PieceTableWalkerChunk,
  Point,
  ResolvedAnchor,
} from '../pieceTable'
export type {
  DocumentSession,
  DocumentSessionApplyEditsOptions,
  DocumentSessionChange,
  DocumentSessionChangeKind,
  DocumentSessionEditHistoryMode,
  DocumentSessionEditSelection,
  DocumentSessionSelectionOptions,
  DocumentSessionSelectionRange,
  DocumentTransaction,
  DocumentTransactionMetadata,
  EditorBufferSession,
  EditorTextBuffer,
  EditorTextBufferChange,
  EditorTextBufferChangeListener,
  EditorTimingMeasurement,
  EditorViewMetadataValue,
  EditorViewScrollPosition,
  EditorViewSession,
} from '../documentSession'
export type { DocumentTextSnapshot, TextSnapshot } from '../documentTextSnapshot'
export type { EditorDocument, TextEdit } from '../tokens'
export type { TextCharacterClass, TextOffsetRange } from '../textRanges'
