export {
  createEditorCapabilityToken,
  createEditorLanguageFeatureToken,
  EDITOR_MINIMAP_FEATURE,
  EDITOR_MINIMAP_FEATURE_ID,
} from '../plugins'
export {
  EditorDecorationStore,
  projectDecorationRangeThroughEdits,
} from '../editor/decorationStore'
export type {
  EditorDecoration,
  EditorDecorationRange,
  EditorDecorationSpec,
  EditorDecorationSurface,
} from '../editor/decorationStore'
export { EDITOR_FIND_FEATURE, EDITOR_FIND_FEATURE_ID } from '../editor/findFeature'
export type { EditorFindFeature } from '../editor/findFeature'
export {
  editorLanguageConfiguration,
  registerEditorLanguageConfiguration,
} from '../editor/languageConfiguration'
export type {
  EditorAutoClosingPair,
  EditorBlockCommentTokens,
  EditorBracketPair,
  EditorCommentTokens,
  EditorEnterAction,
  EditorFoldingRules,
  EditorIndentationRules,
  EditorLanguageConfiguration,
  EditorOnEnterRule,
} from '../editor/languageConfiguration'
export type {
  EditorCapabilityToken,
  EditorCapabilityContribution,
  EditorCapabilityContributionContext,
  EditorCapabilityContributionProvider,
  EditorCommandContribution,
  EditorCommandContributionContext,
  EditorCommandContributionProvider,
  EditorCommandHandler,
  EditorDecorationContribution,
  EditorDecorationContributionContext,
  EditorDecorationContributionProvider,
  EditorEditContribution,
  EditorEditContributionContext,
  EditorEditContributionProvider,
  EditorDisposable,
  EditorGutterContribution,
  EditorGutterRowContext,
  EditorGutterWidthContext,
  EditorHighlighterProvider,
  EditorHighlighterSession,
  EditorHighlighterSessionOptions,
  EditorHighlightResult,
  EditorInjectedTextRow,
  EditorInjectedTextRowProvider,
  EditorInjectedTextRowProviderContext,
  EditorInlineReplacementContext,
  EditorInlineReplacementProvider,
  EditorLanguageFeatureSelector,
  EditorLanguageFeatureToken,
  EditorLogEditorContext,
  EditorLogError,
  EditorLogEvent,
  EditorLogInput,
  EditorLogger,
  EditorLogLevel,
  EditorMinimapDecoration,
  EditorMinimapDecorationPosition,
  EditorMinimapFeature,
  EditorMinimapSectionHeaderStyle,
  EditorOverlaySide,
  EditorPlugin,
  EditorPluginContext,
  EditorPluginLifecycleState,
  EditorResolvedSelection,
  EditorSelectionRange,
  EditorTrackedRanges,
  EditorViewContribution,
  EditorViewContributionContext,
  EditorViewContributionProvider,
  EditorViewContributionUpdateKind,
  EditorViewportSnapshot,
  EditorViewSnapshot,
  EditorVisibleRowSnapshot,
} from '../plugins'
