export {
  createEditorSyntaxSession,
  createEmptySyntaxResult,
  createEmptySyntaxSession,
  createSyntaxLanguageConfiguration,
  createSyntaxProjectionTag,
  createSyntaxSnapshotTag,
  isEditorSyntaxLanguage,
  packEditorTokens,
  packedEditorTokenTransfers,
  styleForTreeSitterCapture,
  treeSitterCapturesToEditorTokens,
  unpackEditorTokens,
} from '../syntax'
export type { PackedEditorTokens } from '../syntax'
export type {
  BracketInfo,
  EditorSyntaxCapture,
  EditorSyntaxDegradedState,
  EditorSyntaxEditSummary,
  EditorSyntaxError,
  EditorSyntaxInjection,
  EditorSyntaxLanguageId,
  EditorSyntaxLanguageConfiguration,
  EditorSyntaxMode,
  EditorSyntaxProjectionTag,
  EditorSyntaxProvider,
  EditorSyntaxRange,
  EditorSyntaxResult,
  EditorSyntaxResultOptions,
  EditorSyntaxServiceRequest,
  EditorSyntaxSession,
  EditorSyntaxSessionOptions,
  EditorSyntaxSnapshotTag,
  FoldRange,
} from '../syntax'
export type { EditorToken, EditorTokenStyle } from '../tokens'
